find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(uh_clap_patch_dir "${CMAKE_CURRENT_LIST_DIR}")
set(uh_clap_source_dir "${UAPMD_DIR}/source/remidy/src/clap")
set(uh_clap_generated "${CMAKE_CURRENT_BINARY_DIR}/generated/clap-note-dialect")
file(GLOB uh_clap_inputs "${uh_clap_source_dir}/*.cpp" "${uh_clap_source_dir}/*.hpp")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    ${uh_clap_inputs} "${uh_clap_patch_dir}/apply.py" "${uh_clap_patch_dir}/note_dialect.h")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${uh_clap_patch_dir}/apply.py"
    "${uh_clap_source_dir}" "${uh_clap_generated}"
    RESULT_VARIABLE uh_clap_result OUTPUT_VARIABLE uh_clap_copies ERROR_VARIABLE uh_clap_error
    OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT uh_clap_result EQUAL 0)
    message(FATAL_ERROR "${uh_clap_error}")
endif()
get_target_property(uh_clap_sources remidy SOURCES)
foreach(uh_name IN LISTS uh_clap_copies)
    set(uh_count 0)
    foreach(uh_source IN LISTS uh_clap_sources)
        get_filename_component(uh_basename "${uh_source}" NAME)
        if(uh_source MATCHES "(^|/)src/clap/" AND uh_basename STREQUAL uh_name)
            list(REMOVE_ITEM uh_clap_sources "${uh_source}")
            math(EXPR uh_count "${uh_count} + 1")
        endif()
    endforeach()
    if(NOT uh_count EQUAL 1)
        execute_process(COMMAND git -C "${UAPMD_DIR}" rev-parse HEAD
            OUTPUT_VARIABLE uh_clap_revision OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(NOT uh_clap_revision)
            set(uh_clap_revision "unknown")
        endif()
        message(FATAL_ERROR "[clap-note-dialect] target: ${uh_clap_source_dir}/${uh_name}; expected one remidy source, found ${uh_count}; UAPMD revision: ${uh_clap_revision}; instructions: ${uh_clap_patch_dir}/README.md")
    endif()
    list(APPEND uh_clap_sources "${uh_clap_generated}/${uh_name}")
endforeach()
set_property(TARGET remidy PROPERTY SOURCES "${uh_clap_sources}")
add_executable(clap_note_dialect_test EXCLUDE_FROM_ALL "${uh_clap_patch_dir}/dialect_test.cpp")
get_target_property(uh_clap_includes remidy INCLUDE_DIRECTORIES)
target_include_directories(clap_note_dialect_test PRIVATE ${uh_clap_includes})
target_link_libraries(clap_note_dialect_test PRIVATE remidy)
if(WIN32)
    add_executable(clap_note_native_ab EXCLUDE_FROM_ALL "${uh_clap_patch_dir}/native_ab.cpp")
    target_include_directories(clap_note_native_ab PRIVATE ${uh_clap_includes})
    target_link_libraries(clap_note_native_ab PRIVATE remidy)
endif()
