find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(uh_state_patch_dir "${CMAKE_CURRENT_LIST_DIR}")
set(uh_state_upstream "${UAPMD_DIR}/source/remidy/src/clap")
set(uh_state_input "${CMAKE_CURRENT_BINARY_DIR}/generated/clap-note-dialect")
set(uh_state_output "${CMAKE_CURRENT_BINARY_DIR}/generated/clap-state-load-error")
set(uh_state_name "PluginInstanceCLAP.States.cpp")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${uh_state_upstream}/${uh_state_name}" "${uh_state_input}/${uh_state_name}"
    "${uh_state_patch_dir}/apply.py")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${uh_state_patch_dir}/apply.py"
    "${uh_state_upstream}" "${uh_state_input}" "${uh_state_output}"
    RESULT_VARIABLE uh_state_result ERROR_VARIABLE uh_state_error OUTPUT_QUIET)
if(NOT uh_state_result EQUAL 0)
    message(FATAL_ERROR "${uh_state_error}")
endif()
get_target_property(uh_state_sources remidy SOURCES)
set(uh_state_count 0)
set(uh_state_unexpected 0)
foreach(uh_source IN LISTS uh_state_sources)
    get_filename_component(uh_basename "${uh_source}" NAME)
    if(uh_basename STREQUAL uh_state_name)
        if(uh_source STREQUAL "${uh_state_input}/${uh_state_name}")
            math(EXPR uh_state_count "${uh_state_count} + 1")
        else()
            math(EXPR uh_state_unexpected "${uh_state_unexpected} + 1")
        endif()
    endif()
endforeach()
if(NOT uh_state_count EQUAL 1 OR NOT uh_state_unexpected EQUAL 0)
    execute_process(COMMAND git -C "${UAPMD_DIR}" rev-parse HEAD
        OUTPUT_VARIABLE uh_state_revision OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(NOT uh_state_revision)
        set(uh_state_revision "unknown")
    endif()
    message(FATAL_ERROR "[clap-state-load-error] target: ${uh_state_input}/${uh_state_name}; expected one note-generated source and no other state sources, found ${uh_state_count}/${uh_state_unexpected}; UAPMD revision: ${uh_state_revision}; instructions: ${uh_state_patch_dir}/README.md")
endif()
list(REMOVE_ITEM uh_state_sources "${uh_state_input}/${uh_state_name}")
list(APPEND uh_state_sources "${uh_state_output}/${uh_state_name}")
set_property(TARGET remidy PROPERTY SOURCES "${uh_state_sources}")

# Test-only plugin: built in target/shim, never scanned or installed.
add_library(clap_state_test_plugin MODULE EXCLUDE_FROM_ALL "${uh_state_patch_dir}/test_plugin.cpp")
get_target_property(uh_state_includes remidy INCLUDE_DIRECTORIES)
target_include_directories(clap_state_test_plugin PRIVATE ${uh_state_includes})
set_target_properties(clap_state_test_plugin PROPERTIES PREFIX "" SUFFIX ".clap")
add_executable(clap_state_backend_test EXCLUDE_FROM_ALL "${uh_state_patch_dir}/backend_test.cpp")
target_include_directories(clap_state_backend_test PRIVATE ${uh_state_includes})
target_link_libraries(clap_state_backend_test PRIVATE remidy)
