if(WIN32)
    set(uh_vst3_patch_dir "${CMAKE_CURRENT_LIST_DIR}")
    include("${uh_vst3_patch_dir}/apply.cmake")
    set(uh_vst3_source "${UAPMD_DIR}/source/remidy/src/vst3/ClassModuleInfo.cpp")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${uh_vst3_source}")
    set(uh_patched_loader "${CMAKE_CURRENT_BINARY_DIR}/generated/windows-vst3-loader/ClassModuleInfo.cpp")
    get_target_property(uh_remidy_sources remidy SOURCES)
    set(uh_loader_count 0)
    foreach(uh_source IN LISTS uh_remidy_sources)
        if(uh_source MATCHES "(^|/)src/vst3/ClassModuleInfo\\.cpp$")
            list(REMOVE_ITEM uh_remidy_sources "${uh_source}")
            math(EXPR uh_loader_count "${uh_loader_count} + 1")
        endif()
    endforeach()
    if(NOT uh_loader_count EQUAL 1)
        uh_vst3_patch_error("${uh_vst3_source}"
            "remidy target must contain exactly 1 ClassModuleInfo.cpp source, found ${uh_loader_count}")
    endif()
    uh_patch_windows_vst3_loader("${uh_vst3_source}" "${uh_patched_loader}")
    set_property(TARGET remidy PROPERTY SOURCES "${uh_remidy_sources}")
    target_sources(remidy PRIVATE "${uh_patched_loader}")

    add_executable(windows_vst3_binary_test EXCLUDE_FROM_ALL "${uh_vst3_patch_dir}/binary_test.cpp")
    target_include_directories(windows_vst3_binary_test PRIVATE "${uh_vst3_patch_dir}")
    target_link_libraries(windows_vst3_binary_test PRIVATE remidy)
endif()
